version: '2'
services:
    account-app:
        image: account
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_CLOUD_CONSUL_HOST=consul
            - SPRING_CLOUD_CONSUL_PORT=8500
            - JHIPSTER_SLEEP=30 # gives time for the database to boot before the application
    consul:
        extends:
            file: consul.yml
            service: consul

    consul-config-loader:
        extends:
            file: consul.yml
            service: consul-config-loader
